#!/system/bin/sh

# **************************************************************
# Add Synapse support
# **************************************************************

UKM=/data/UKM;
BB=$UKM/busybox;
UCI_CONFIG=$UKM/config.json;
DEBUG=$UKM/debug;
UCI_FILE=$UKM/uci;
UCI_XBIN=/system/xbin/uci;

# Delete default uci config in case kernel has one already to avoid duplicates.

if [ -e "/sbin/uci" ]; then
	$BB rm -f /sbin/uci
fi


# Set SElinux to permisive on boot

$BB echo "0" >/sys/fs/selinux/enforce

# Reset profiles to default

$BB echo "Custom" > $UKM/files/lmk_prof
$BB echo "0" > $UKM/files/volt_prof;
$BB echo "0" > $UKM/files/dropcaches_prof;

# Symlink uci file to xbin in case it's not found.

if [ ! -e $UCI_XBIN ]; then
	$BB mount -o remount,rw /system
	$BB mount -t rootfs -o remount,rw rootfs
	
	$BB chmod 755 $UCI_FILE
	$BB ln -s $UCI_FILE $UCI_XBIN
	$BB chmod 755 $UCI_XBIN
	
	$BB mount -t rootfs -o remount,ro rootfs
	$BB mount -o remount,ro /system
fi

# If uci files does not have 755 permissions, set permissions.

if [ `$BB stat -c %a $UCI_FILE` -lt "755" ]; then
	$BB chmod 755 $UCI_FILE
fi

if [ `$BB stat -c %a $UCI_XBIN` -lt "755" ]; then
	$BB mount -o remount,rw /system
	$BB mount -t rootfs -o remount,rw rootfs
	$BB chmod 755 $UCI_XBIN
	$BB mount -t rootfs -o remount,ro rootfs
	$BB mount -o remount,ro /system
fi

